---
- hosts: all
  become: true
  tasks:
  - name: Configure node ip
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
      create: yes

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="192.168.50.10" --pod-network-cidr=192.168.0.0/16 --apiserver-cert-extra-sans="192.168.50.10" --node-name k8s-master
  
  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    with_items:
      - mkdir -p /home/vagrant/.kube
      - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
      - chown vagrant:vagrant /home/vagrant/.kube/config
  
  - name: Install calico pod network
    become: false
    command: kubectl apply -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

  - name: Install Helm
    command: "{{ item }}"
    with_items:
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh

  - name: Add Helm repo
    command: "{{ item }}"
    with_items:
      - helm repo add stable https://kubernetes-charts.storage.googleapis.com/
  
  - name: Enable force color in bash
    lineinfile:
      path: /home/vagrant/.bashrc
      regexp: '^#force_color_prompt=yes'
      line: 'force_color_prompt=yes'
  
  - name: Set kubectl and helm aliases
    blockinfile:
      path: /home/vagrant/.bashrc
      block: |
        alias k=kubectl
        alias h=helm

  - name: Set kubectl and helm code completion
    blockinfile:
      path: /home/vagrant/.bashrc
      block: |
        source <(kubectl completion bash)
        source <(kubectl completion bash | sed s/kubectl/k/g)
        source <(helm completion bash)
        source <(helm completion bash | sed s/helm/h/g)